application: food-enthusiast
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: .*
  script: main.app

- url: /js
  static_dir: js

libraries:
- name: webapp2
  version: latest
